categories:
  - title: ':sparkles: New Features'
    label: ':sparkles: new feature'
  - title: ':zap: Improvements'
    label: ':zap: improvement'
  - title: ':bug: Bug Fixes'
    labels:
      - ':butterfly: bugfix'
      - ':bug: bug'
  - title: ':lock: Security and others'
    labels:
      - ':lock: security'
      - '⬆️ dependencies'
category-template: '### $TITLE'
template: |
  <img src="https://raw.githubusercontent.com/tjarbo/discord-moodle-bot/version-2/logo.svg" alt="Notification Service for Moodle - Logo" align="right" width="128">

  ## Hey there :wave:
  <<ENTER TEXT>>

  To stay up to date and get notified as soon as a new release is available, click on *Watch* in the upper right corner, then *Custom* and activate ✅ *Releases* and *Discussions* (so that your inbox is not spammed 😉 )! And if you like the Notification Service, give it a 🌟  - thank you 🤩!
  $CHANGES

  ### Available Docker Images:
  - `tjarbo/notification-service:latest` - the latest release
  - `tjarbo/notification-service:next` - the latest commit of default branch (⚠️ maybe unstable)

  All image tags can be found [here](https://hub.docker.com/r/tjarbo/notification-service/tags).

  ---
  [Wiki](https://docs.tjarbo.me/moodle-notification-service/2.0.0/home) · [FAQ](https://github.com/tjarbo/discord-moodle-bot/discussions/categories/q-a) · [Issues](https://github.com/tjarbo/discord-moodle-bot/issues) · [All Releases](https://github.com/tjarbo/discord-moodle-bot/releases)